apiVersion: apps/v1 
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
      tier: data
  template:
    metadata:
      name: api
      labels:
        app: api
        tier: data
    spec:
      containers:
        - name: redis
          image: "lzravr/api-hpa:php"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
