kind: HorizontalPodAutoscaler 
apiVersion: autoscaling/v2beta1 
metadata: 
  name: api
spec: 
  maxReplicas: 8 
  minReplicas: 1 
  scaleTargetRef: 
    apiVersion: apps/v1 
    kind: Deployment 
    name: api
  metrics: 
  - type: Resource 
    resource: 
      name: memory
      targetAverageValue: 30Mi